#ifndef ACQUISITIONCONFIG_H
#define ACQUISITIONCONFIG_H

// Acquisition parameters
#define PRE_TRIGGER_SAMPLES (128)
#define POST_TRIGGER_SAMPLES (512)
#define RECORDS_PER_BUFFER (1000)
#define BUFFERS_PER_ACQUISITION (500)

// Processing parameters
#define NUM_AVERAGE_SIGNALS (10)

#endif // ACQUISITIONCONFIG_H
