#ifndef ACQUISITIONCONFIG_H
#define ACQUISITIONCONFIG_H

#define PRE_TRIGGER_SAMPLES (128)
#define POST_TRIGGER_SAMPLES (512)
#define RECORDS_PER_BUFFER (500)
#define BUFFERS_PER_ACQUISITION (1000)

#endif // ACQUISITIONCONFIG_H
